include:
  - local: '/ci/abstract_jobs.yml'
  - local: '/ci/ci-config.yml'


stages:
  - build
  - build_and_source_test
  - built_test_and_deploy
  - deploy

"docker retag php image":
  extends: .abstract_jobs.docker
  stage: .pre
  script:
    - docker pull php:$PHP_IMAGE_TAG
    - docker tag php:$PHP_IMAGE_TAG $REGISTRY/php:$PHP_IMAGE_TAG
    - docker push $REGISTRY/php:$PHP_IMAGE_TAG
  rules:
    - if: $DOCKER_RETAG_PHP_IMAGE == "true"
      when: on_success
    - when: never

"docker: build base, source and test-source image":
  extends: .abstract_jobs.docker
  stage: build
  script:
    - build_and_push base
    - build_and_push source
    - build_and_push test-source

"php unit: all tests source":
  extends: .abstract_jobs.php_unit_test
  stage: build_and_source_test
  image:
    name: "$REGISTRY/test-source:commit$CI_COMMIT_SHA-$PHP_IMAGE_TAG"
  rules:
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
      when: on_success
    - when: never

"docker: build dev, build, built and test-built image":
  extends: .abstract_jobs.docker
  stage: build_and_source_test
  script:
    - build_and_push build
    - build_and_push built
    - build_and_push test-built
    - build_and_push dev
  rules:
    - if: $DOCKER_BUILD_BUILD == "true"
      when: on_success
    - when: never

"php unit: all tests built":
  extends: .abstract_jobs.php_unit_test
  stage: built_test_and_deploy
  image:
    name: "$REGISTRY/test-built:commit$CI_COMMIT_SHA-$PHP_IMAGE_TAG"
  rules:
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "true"
      when: on_success
    - when: never

"php unit: all tests built with ldap":
  extends: .abstract_jobs.php_unit_test_with_ldap
  stage: built_test_and_deploy
  image:
    name: "$REGISTRY/test-built:commit$CI_COMMIT_SHA-$PHP_IMAGE_TAG"
  script:
    - cd /tine/tests/tine20/
    - php /tine/tine20/vendor/bin/phpunit --color --debug --exclude-group longrunning,needsbuild,nogitlabci_ldap CiTestSuite$CI_NODE_INDEX
  rules:
    - if: $PHP_UNIT_ALL_TESTS_BUILT_WITH_LDAP == "true"
      when: on_success
    - when: never

"docker: push base, source and test-source image":
  extends: .abstract_jobs.docker
  stage: built_test_and_deploy
  script:
    - pull_tag_push base commit$CI_COMMIT_SHA-$PHP_IMAGE_TAG $CI_COMMIT_REF_NAME-$PHP_IMAGE_TAG
    - pull_tag_push source commit$CI_COMMIT_SHA-$PHP_IMAGE_TAG $CI_COMMIT_REF_NAME-$PHP_IMAGE_TAG
    - pull_tag_push test-source commit$CI_COMMIT_SHA-$PHP_IMAGE_TAG $CI_COMMIT_REF_NAME-$PHP_IMAGE_TAG

"docker: push build, built, test-built and dev image":
  extends: .abstract_jobs.docker
  stage: deploy
  script:
    - pull_tag_push build commit$CI_COMMIT_SHA-$PHP_IMAGE_TAG $CI_COMMIT_REF_NAME-$PHP_IMAGE_TAG
    - pull_tag_push built commit$CI_COMMIT_SHA-$PHP_IMAGE_TAG $CI_COMMIT_REF_NAME-$PHP_IMAGE_TAG
    - pull_tag_push test-built commit$CI_COMMIT_SHA-$PHP_IMAGE_TAG $CI_COMMIT_REF_NAME-$PHP_IMAGE_TAG
    - pull_tag_push dev commit$CI_COMMIT_SHA-$PHP_IMAGE_TAG $CI_COMMIT_REF_NAME-$PHP_IMAGE_TAG
  rules:
    - if: $DOCKER_BUILD_BUILD == "true"
      when: on_success
    - when: never
