site_name: tine groupware docs
site_url: https://www.tine-groupware.de
repo_url: https://github.com/tine-groupware/tine

theme:
  name: material
  logo: images/logo.svg
  favicon: images/favicon.png
  palette:
    primary: blue



#nav:
#  - 'User Guide': 'user-guide.md'
#  - 'tine Admins': 'user-guide.md'
#  - 'sys Admins': '/docker/*'
#  - 'Developers': '/bugs/'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tine-groupware/tine
      name: tine groupware on Github
    - icon: fontawesome/solid/globe
      link: https://transifex.com/tine
      name: translations on transifex

plugins:
  - search
  - awesome-pages
  - i18n:
      default_language: en
      docs_structure: suffix
      languages:
        default:
          name: Default (en)
          build: true
        en:
          name: English
          build: true
        de:
          name: Deutsch
          build: true