[template]
prefix = "/nginx"
src = "nginx.conf.tmpl"
dest = "/etc/nginx/nginx.conf"
owner = "root"
mode = "0644"
keys = [
    "/client/max/body/size",
    "/keepalive/timeout",
    "/tcp/nopush",
    "/gzip",
    "/gzip/static",
    "/brotli",
    "/brotli/comp/level"
]
check_cmd = "/usr/sbin/nginx -t -c {{.src}}"