variables:
  PHP_UNIT_ALL_TESTS_SOURCE: "true"
  PHP_UNIT_ALL_TESTS_BUILT: "true"
  PHP_UNIT_ALL_TESTS_BUILT_WITH_LDAP: "false"
  MAJOR_COMMIT_REF_NAME: "2018.11"
  DOCKER_BUILD_BASE_IMAGE: "false"
  DOCKER_BUILD_DEPENDENCY_IMAGE: "false"
  DOCKER_BUILD_BUILD: "true"
  PHP_UNIT_NOGITLABCI_TESTS_BUILT: "false"
  PHP_STAN_ANALYSES: "true"
  NO_CACHE: "true"
  RUN_CI_PIPELINE: "true"
  PUSH_TO_DOCKERHUB: "false"
  DOCKERHUB_TAG: "dev"
  PHP_UNIT_SERVERTESTS: "true"
  DATABASE_IMAGE: "mariadb:10.5.3"
  REDIS_IMAGE: "redis:5.0.5"