# only for customapps

phpcs:
  stage: test
  image: composer
  needs: []
  before_script:
    - composer require squizlabs/php_codesniffer
    - composer require micheh/phpcs-gitlab
  script:
    - ./vendor/bin/phpcs -s --report=full --standard=PSR12
      --report-\\Micheh\\PhpCodeSniffer\\Report\\Gitlab=phpcs-report.json ./lib
      --exclude=PSR1.Classes.ClassDeclaration,Squiz.Classes.ValidClassName,PSR2.Classes.PropertyDeclaration,PSR2.Methods.MethodDeclaration
      --extensions=php
  artifacts:
    reports:
      codequality: phpcs-report.json
  rules:
    - if: $CODE_ANALYSIS_PHPCS_STRICT == "true"
      allow_failure: false
    - allow_failure: true

parallel-lint:
  stage: test
  image: composer
  needs: []
  before_script:
    - composer require php-parallel-lint/php-parallel-lint=dev-master
  script:
    - ./vendor/bin/parallel-lint --gitlab ./lib/ >> parallel-lint-report.json || true
    - ./vendor/bin/parallel-lint ./lib/
  artifacts:
    reports:
      codequality: parallel-lint-report.json
  rules:
    - if: $CODE_ANALYSIS_PARALLEL_LINT_STRICT == "false"
      allow_failure: true
    - allow_failure: false
