# only for customapps
phpstan:
  stage: test
  image: composer
  needs: []
  before_script:
    - composer require phpstan/phpstan
  script:
    - 'test -f phpstan.neon.dist || printf "parameters:\n\tlevel: ${CODE_ANALYSIS_PHPSTAN_LEVEL:-2}\n\tscanDirectories:\n\t- ${CI_BUILDS_DIR}/tine20/tine20/tine20\n" >> phpstan.neon.dist'
    - if test "${CI_PROJECT_NAME}" != "tine20"; then git clone -b $TINE20_BRANCH --single-branch --depth 1 $TINE20_REPO_URL ${CI_BUILDS_DIR}/tine20/tine20; fi
    - (cd tine20/tine20; composer install --ignore-platform-reqs --no-interaction)
    - ./vendor/bin/phpstan analyse --no-progress --error-format=gitlab lib/ >> phpstan-report.json || true
    - ./vendor/bin/phpstan analyse --no-progress -vvv lib/ | tee phpstan-report.json
  artifacts:
    reports:
      codequality: phpstan-report.json
  rules:
    - if: $CODE_ANALYSIS_PHPSTAN_STRICT == "true"
      allow_failure: false
    - allow_failure: true

phpcs:
  stage: test
  image: composer
  needs: []
  before_script:
    - composer require squizlabs/php_codesniffer
    - composer require micheh/phpcs-gitlab
  script:
    - ./vendor/bin/phpcs -s --report=full --standard=PSR12
      --report-\\Micheh\\PhpCodeSniffer\\Report\\Gitlab=phpcs-report.json ./lib
      --exclude=PSR1.Classes.ClassDeclaration,Squiz.Classes.ValidClassName,PSR2.Classes.PropertyDeclaration,PSR2.Methods.MethodDeclaration
      --extensions=php
  artifacts:
    reports:
      codequality: phpcs-report.json
  rules:
    - if: $CODE_ANALYSIS_PHPCS_STRICT == "true"
      allow_failure: false
    - allow_failure: true

parallel-lint:
  stage: test
  image: composer
  needs: []
  before_script:
    - composer require php-parallel-lint/php-parallel-lint=dev-master
  script:
    - ./vendor/bin/parallel-lint --gitlab ./lib/ >> parallel-lint-report.json || true
    - ./vendor/bin/parallel-lint ./lib/
  artifacts:
    reports:
      codequality: parallel-lint-report.json
  rules:
    - if: $CODE_ANALYSIS_PARALLEL_LINT_STRICT == "false"
      allow_failure: true
    - allow_failure: false
