housekeeping_uninterruptible:
  variables:
    KUBERNETES_CPU_REQUEST: 10m
    KUBERNETES_MEMORY_REQUEST: 100Mi
    GIT_STRATEGY: none
  stage: build1
  interruptible: false
  allow_failure: true
  script:
    - >-
      echo "This job dose not build anything.";
      echo "Its is only here to make the pipeline uninterruptible.";
      echo "This job should not run for merge requests and feature branches,";
      echo "but it should run on main branches and for customer apps.";
      echo "";
      echo "gitlab-ci.yml ref:";
      echo "  interruptible:";
      echo "    When Auto-cancel redundant pipelines is enabled, a pipeline is";
      echo "    immediately canceled when a new pipeline starts on the same";
      echo "    branch if either of the following is true:";
      echo "    - All jobs in the pipeline are set as interruptible.";
      echo "    - Any uninterruptible jobs have not started yet.";
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /(^feat)|(^pu)|(change)/
      when: never
    - when: on_success

# ============ stage: housekeeping ===========================

docker_populate_cache:
  extends: .abstract_jobs.docker
  stage: housekeeping
  script:
    - ${CI_BUILDS_DIR}/tine20/tine20/ci/scripts/push_image_to_cache.sh base || true
    - ${CI_BUILDS_DIR}/tine20/tine20/ci/scripts/push_image_to_cache.sh source || true
    - ${CI_BUILDS_DIR}/tine20/tine20/ci/scripts/push_image_to_cache.sh test-source || true
    - ${CI_BUILDS_DIR}/tine20/tine20/ci/scripts/push_image_to_cache.sh build || true
    - ${CI_BUILDS_DIR}/tine20/tine20/ci/scripts/push_image_to_cache.sh built || true
    - ${CI_BUILDS_DIR}/tine20/tine20/ci/scripts/push_image_to_cache.sh test-built || true
    - ${CI_BUILDS_DIR}/tine20/tine20/ci/scripts/push_image_to_cache.sh dev || true
  allow_failure: true # a failure is a problem, but the pipeline should not fail
  interruptible: false
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - when: on_success
