stages:
  - merge1
  - merge2
  - merge3

.abstract.merge:
  variables:
    MERGENONINTERACTIVE: "true" # "false" is also true! Runs not interactive if the variable exists.
  image: ${REGISTRY}/test-source-commit:${IMAGE_TAG}
  before_script:
    - apk add git
    - cp $DOCKER_GIT_CONFIG ~/.gitconfig
    - git clone --branch gitlab https://gitlab.metaways.net/tine20/buildscripts.git $CI_BUILDS_DIR/tine20/buildscripts
    - git config --global user.email "gitlabci@metaways.de"
    - git config --global user.name "gitlabci"
    - cd $CI_BUILDS_DIR/tine20/tine20
    - git remote add customers https://gitlab.metaways.net/tine20/tine20.git
    - git fetch

merge:
  stage: merge1
  extends: .abstract.merge
  script:
    - cd $CI_BUILDS_DIR/tine20/tine20/tine20
    - ${CI_BUILDS_DIR}/tine20/tine20/ci/scripts/merge.sh
  rules:
    - if: $AUTO_MERGE_VAR == "true"
      when: on_success
    - when: never