send-pipeline-status:
  extends: .abstract_jobs.docker
  stage: notify
  script:
    - !reference [.lib, script]
    - pipeline_status_send
  rules:
    - if: $SEND_PIPELINE_STATUS == "false"
      when: never
    - if: $SEND_PIPELINE_STATUS == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /send-pipeline-status/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SEND_PIPELINE_STATUS_SCHEDULE != "false"