js-e2e-tests-source:
  extends: .abstract_jobs.e2e_test
  stage: test
  needs:
    - docker_build_source
  variables:
    ARG_COPY_SOURCE: "true"
    ARG_IMAGE: test-source
  interruptible: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $JS_E2E_TESTS_SOURCE == "false"
      when: never
    - if: $JS_E2E_TESTS_SOURCE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $JS_E2E_TESTS_SOURCE_MERGE_REQUEST != "false"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /js-e2e-tests-source/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $JS_E2E_TESTS_SOURCE_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG