"php unit: all tests source":
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-source
    ARG_COPY_SOURCE: "true"
    NODE_TOTAL: 1
    NODE_INDEX: 1
  needs:
    - docker_build_source
  stage: test
  timeout: 45m
  interruptible: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "never"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_PARALLEL == "true"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
      when: on_success
    - when: never

"php unit: all tests source, parallel":
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-source
    ARG_COPY_SOURCE: "true"
  stage: test
  needs:
    - docker_build_source
  timeout: 45m
  parallel: 5
  interruptible: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "never"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_PARALLEL == "false"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
      when: on_success
    - when: never

"php unit: servertests source":
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-source
    ARG_COPY_SOURCE: "true"
    ARG_TEST: AllServerTests
  stage: test
  needs:
    - docker_build_source
  timeout: 30m
  interruptible: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_SERVERTESTS == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_SERVERTESTS == "true"
      when: on_success
    - when: never

"php unit: tests with postfixmultiinstance":
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-source
    ARG_COPY_SOURCE: "true"
    ARG_POSTFIX_INIT_SQL_PATH: /config/sql/postfixmultiinstance_tables.sql
    TINE20_EMAIL_SMTP: "active:true,backend:postfixmultiinstance,hostname:postfix,port:25,ssl:none,auth:none,name:postfix,primarydomain:mail.test,instanceName:tine.test,postfixmultiinstance_host:db,postfixmultiinstance_dbname:postfix,postfixmultiinstance_username:tine20,postfixmultiinstance_password:tine20pw"
  stage: test
  needs:
    - docker_build_source
  timeout: 45m
  interruptible: true
  parallel: 5
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_TESTS_POSTFIXMULTIINSTANCE == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_TESTS_POSTFIXMULTIINSTANCE == "true"
      when: on_success
    - when: never

"php unit: setup tests source":
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-source
    ARG_COPY_SOURCE: "true"
    ARG_TEST_PATH_FROM_TINE20ROOT: tests/setup/
  stage: test
  needs:
    - docker_build_source
  timeout: 90m
  interruptible: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_SETUP_TESTS == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_SETUP_TESTS == "true"
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"
      changes:
        - tine20/Setup/**/*
    - when: never

"php unit: all tests built":
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-built
  stage: test
  needs:
    - docker_build_built
  parallel: 5
  timeout: 45m
  interruptible: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "true"
      when: on_success
    - when: never

"php unit: nogitlabci tests built":
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-built
    ARG_EXCLUDE_GROUP: ""
    ARG_GROUP: "nogitlabci"
  stage: test
  needs:
    - docker_build_built
  parallel: 5
  allow_failure: true
  timeout: 30m
  interruptible: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "true"
      when: on_success
    - when: never

"php unit: all tests built with ldap":
  extends: .abstract_jobs.php_unit_ldap
  variables:
    ARG_IMAGE: test-built
  stage: test
  needs:
    - docker_build_built
  parallel: 5
  timeout: 30m
  interruptible: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT_WITH_LDAP == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_ALL_TESTS_BUILT_WITH_LDAP == "true"
      when: on_success
    - when: never
