# todo if gitlab version >= 14.3 use gitlab "!reference [.>abstractjob<, rules]" to reduce rules copying

.php-unit-all-tests-source:
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-source
    ARG_COPY_SOURCE: "true"
  needs:
    - docker_build_source
  stage: test
  timeout: 2h
  interruptible: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_SOURCE_MERGE_REQUEST != "false"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-source/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_SOURCE_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG
php-unit-all-tests-source-sequential:
  extends: .php-unit-all-tests-source
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_TYPE != "sequential"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_SOURCE_MERGE_REQUEST != "false"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-source/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_SOURCE_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG
php-unit-all-tests-source-parallel:
  extends: .php-unit-all-tests-source
  timeout: 45m
  parallel: 5
  rules:
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_TYPE != "parallel"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_SOURCE_MERGE_REQUEST != "false"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-source/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_SOURCE_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG
php-unit-all-tests-source-matrix:
  extends: .php-unit-all-tests-source
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  parallel:
    matrix:
      - PROVIDER:
          - "mariadb:10.4"
          - "mariadb:10.3"
          - "mariadb:10.2"
          - "mariadb:10.1"
          - "mariadb:10.0"
          - "mysql:8.0"
          - "mysql:5.7"
          - "mysql:5.6"
  rules:
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_TYPE != "matrix"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_SOURCE_MERGE_REQUEST != "false"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-source/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_SOURCE_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG


.php-unit-all-tests-source-postfixmultiinstance:
  extends: .php-unit-all-tests-source
  variables:
    ARG_POSTFIX_INIT_SQL_PATH: /config/sql/postfixmultiinstance_tables.sql
    TINE20_EMAIL_SMTP: "active:true,backend:postfixmultiinstance,hostname:postfix,port:25,ssl:none,auth:none,name:postfix,primarydomain:mail.test,instanceName:tine.test,postfixmultiinstance_host:db,postfixmultiinstance_dbname:postfix,postfixmultiinstance_username:tine20,postfixmultiinstance_password:tine20pw"
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE  == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE  == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-source-postfixmultiinstance/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG
php-unit-all-tests-source-postfixmultiinstance-sequential:
  extends: .php-unit-all-tests-source-postfixmultiinstance
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE_TYPE != "sequential"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE  == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE  == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-source-postfixmultiinstance/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG
php-unit-all-tests-source-postfixmultiinstance-parallel:
  extends: .php-unit-all-tests-source-postfixmultiinstance
  timeout: 45m
  parallel: 5
  rules:
    - if: $PHP_ALL_UNIT_TESTS_SOURCE_POSTFIXMULTIINSTANCE_TYPE != "parallel"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE  == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE  == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-source-postfixmultiinstance/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_SOURCE_POSTFIXMULTIINSTANCE_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG


php-unit-setup-tests-source:
  extends: .php-unit-all-tests-source
  variables:
    ARG_TEST_PATH_FROM_TINE20ROOT: tests/setup/
  timeout: 90m
  allow_failure: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_SETUP_TESTS_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_SETUP_TESTS_SOURCE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_SETUP_TESTS_SOURCE_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-setup-tests-source/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_SETUP_TESTS_SOURCE_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG


php-unit-servertests-source:
  extends: .php-unit-all-tests-source
  variables:
    ARG_TEST: AllServerTests
  timeout: 30m
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_SERVERTESTS_SOURCE == "false"
      when: never
    - if: $PHP_UNIT_SERVERTESTS_SOURCE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_SERVERTESTS_SOURCE_MERGE_REQUEST != "false"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-servertests-source/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_SERVERTESTS_SOURCE_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG


.php-unit-all-tests-built:
  extends: .php-unit-all-tests-source
  variables:
    ARG_IMAGE: test-built
  needs:
    - docker_build_built
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_BUILT_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-built/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_BUILT_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG
php-unit-all-tests-built-sequential:
  extends: .php-unit-all-tests-built
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_ALL_TESTS_BUILT_TYPE != "sequential"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_BUILT_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-built/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_BUILT_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG
    - when: never
php-unit-all-tests-built-parallel:
  extends: .php-unit-all-tests-built
  timeout: 45m
  parallel: 5
  rules:
    - if: $PHP_UNIT_ALL_TESTS_BUILT_TYPE != "parallel"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_BUILT_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-built/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_BUILT_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG

.php-unit-nogitlabci-tests-built:
  extends: .php-unit-all-tests-built
  variables:
    ARG_EXCLUDE_GROUP: ""
    ARG_GROUP: "nogitlabci"
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "false"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_NOGITLABCI_TESTS_BUILT_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-nogitlabci-tests-built/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_NOGITLABCI_TESTS_BUILT_SCHEDULE != "false"
  allow_failure: true
php-unit-nogitlabci-tests-built-sequential:
  extends: .php-unit-nogitlabci-tests-built
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT_TYPE != "sequential"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "false"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_NOGITLABCI_TESTS_BUILT_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-nogitlabci-tests-built/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_NOGITLABCI_TESTS_BUILT_SCHEDULE != "false"
php-unit-nogitlabci-tests-built-parallel:
  extends: .php-unit-nogitlabci-tests-built
  timeout: 30m
  parallel: 5
  rules:
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT_TYPE != "parallel"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "false"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_NOGITLABCI_TESTS_BUILT_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-nogitlabci-tests-built/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_NOGITLABCI_TESTS_BUILT_SCHEDULE != "false"


.php-unit-all-tests-ldap-built:
  extends: .abstract_jobs.php_unit_ldap
  variables:
    ARG_IMAGE: test-built
  stage: test
  needs:
    - docker_build_built
  timeout: 2h
  interruptible: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_LDAP_BUILD == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_LDAP_BUILD == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_LDAP_BUILD_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-ldap-built/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_LDAP_BUILD_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG
phpunit-all-tests-built-ldap-sequential:
  extends: .php-unit-all-tests-ldap-built
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_ALL_TESTS_LDAP_BUILD_TYPE != "sequential"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_LDAP_BUILD == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_LDAP_BUILD == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_LDAP_BUILD_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-ldap-built/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_LDAP_BUILD_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG
php-unit-all-tests-built-ĺdap-parallel:
  extends: .php-unit-all-tests-ldap-built
  timeout: 45m
  parallel: 5
  rules:
    - if: $PHP_UNIT_ALL_TESTS_LDAP_BUILD_TYPE != "parallel"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_LDAP_BUILD == "false"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_LDAP_BUILD == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PHP_UNIT_ALL_TESTS_LDAP_BUILD_MERGE_REQUEST == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /php-unit-all-tests-ldap-built/
    - if: $CI_PIPELINE_SOURCE == "schedule" && $PHP_UNIT_ALL_TESTS_LDAP_BUILD_SCHEDULE != "false"
    - if: $CI_COMMIT_TAG
