# todo if gitlab version >= 14.3 use gitlab "!reference [.>abstractjob<, rules]" to reduce rules copying

.php-unit-all-test-source:
  extends: .abstract_jobs.php_unit
  variables:
    ARG_IMAGE: test-source
    ARG_COPY_SOURCE: "true"
  needs:
    - docker_build_source
  stage: test
  timeout: 2h
  interruptible: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
      when: on_success
    - when: never
"php unit - all tests - source - sequential":
  extends: .php-unit-all-test-source
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_TYPE != "sequential"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
      when: on_success
    - when: never
"php unit - all tests - source - parallel":
  extends: .php-unit-all-test-source
  timeout: 45m
  parallel: 5
  rules:
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_TYPE != "parallel"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
      when: on_success
    - when: never
"php unit - all tests - source - matrix":
  extends: .php-unit-all-test-source
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  timeout: 45m
  parallel:
    matrix:
      - PROVIDER:
          - "mariadb:10.6"
          - "mariadb:10.5"
          - "mariadb:10.4"
          - "mariadb:10.3"
          - "mariadb:10.2"
          - "mysql:8.0"
          - "mysql:5.7"
  rules:
    - if: $PHP_UNIT_ALL_TESTS_SOURCE_TYPE != "matrix"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_ALL_TESTS_SOURCE == "true"
      when: on_success
    - when: never


.php-unit-all-tests-source-postfixmultiinstance:
  extends: .php-unit-all-test-source
  variables:
    ARG_POSTFIX_INIT_SQL_PATH: /config/sql/postfixmultiinstance_tables.sql
    TINE20_EMAIL_SMTP: "active:true,backend:postfixmultiinstance,hostname:postfix,port:25,ssl:none,auth:none,name:postfix,primarydomain:mail.test,instanceName:tine.test,postfixmultiinstance_host:db,postfixmultiinstance_dbname:postfix,postfixmultiinstance_username:tine20,postfixmultiinstance_password:tine20pw"
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_TESTS_POSTFIXMULTIINSTANCE == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_TESTS_POSTFIXMULTIINSTANCE == "true"
      when: on_success
    - when: never
"php unit - all tests - source - postfixmultiinstance - sequential":
  extends: .php-unit-all-tests-source-postfixmultiinstance
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_TESTS_POSTFIXMULTIINSTANCE_TYPE != "sequential"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_TESTS_POSTFIXMULTIINSTANCE == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_TESTS_POSTFIXMULTIINSTANCE == "true"
      when: on_success
    - when: never
"php unit - all test - source - postfixmultiinstance - parallel":
  extends: .php-unit-all-tests-source-postfixmultiinstance
  timeout: 45m
  parallel: 5
  rules:
    - if: $PHP_UNIT_TESTS_POSTFIXMULTIINSTANCE_TYPE != "parallel"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_TESTS_POSTFIXMULTIINSTANCE == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_TESTS_POSTFIXMULTIINSTANCE == "true"
      when: on_success
    - when: never


"php unit - setup tests - source":
  extends: .php-unit-all-test-source
  variables:
    ARG_TEST_PATH_FROM_TINE20ROOT: tests/setup/
  timeout: 90m
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_SETUP_TESTS == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_SETUP_TESTS == "true"
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"
      changes:
        - tine20/Setup/**/*
    - when: never


"php unit - servertests - source":
  extends: .php-unit-all-test-source
  variables:
    ARG_TEST: AllServerTests
  timeout: 30m
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_SERVERTESTS == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_SERVERTESTS == "true"
      when: on_success
    - when: never


.php-unit-all-test-built:
  extends: .php-unit-all-test-source
  variables:
    ARG_IMAGE: test-built
  needs:
    - docker_build_built
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "true"
      when: on_success
    - when: never
"php unit - all tests - built - sequential":
  extends: .php-unit-all-test-built
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_ALL_TESTS_BUILT_TYPE != "sequential"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "true"
      when: on_success
    - when: never
"php unit - all test - built - parallel":
  extends: .php-unit-all-test-built
  timeout: 45m
  parallel: 5
  rules:
    - if: $PHP_UNIT_ALL_TESTS_BUILT_TYPE != "parallel"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_ALL_TESTS_BUILT == "true"
      when: on_success
    - when: never


.php-unit-nogitlabci-test-built:
  extends: .php-unit-all-test-built
  variables:
    ARG_EXCLUDE_GROUP: ""
    ARG_GROUP: "nogitlabci"
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "true"
      when: on_success
    - when: never
  allow_failure: true
"php unit - nogitlabci tests - built - sequential":
  extends: .php-unit-nogitlabci-test-built
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT_TYPE != "sequential"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "true"
      when: on_success
    - when: never
"php unit - nogitlabci test - built - parallel":
  extends: .php-unit-nogitlabci-test-built
  timeout: 30m
  parallel: 5
  rules:
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT_TYPE != "parallel"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_NOGITLABCI_TESTS_BUILT == "true"
      when: on_success
    - when: never


.php-unit-all-test-ldap-built:
  extends: .abstract_jobs.php_unit_ldap
  variables:
    ARG_IMAGE: test-built
  stage: test
  needs:
    - docker_build_built
  timeout: 2h
  interruptible: true
  rules:
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT_WITH_LDAP == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_ALL_TESTS_BUILT_WITH_LDAP == "true"
      when: on_success
    - when: never
"php unit - all tests - built - ldap - sequential":
  extends: .php-unit-all-test-ldap-built
  variables:
    NODE_TOTAL: 1
    NODE_INDEX: 1
  rules:
    - if: $PHP_UNIT_ALL_TESTS_BUILT_WITH_LDAP_TYPE != "sequential"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT_WITH_LDAP == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_ALL_TESTS_BUILT_WITH_LDAP == "true"
      when: on_success
    - when: never
"php unit - all test - built - ldap - parallel":
  extends: .php-unit-all-test-ldap-built
  timeout: 45m
  parallel: 5
  rules:
    - if: $PHP_UNIT_ALL_TESTS_BUILT_WITH_LDAP_TYPE != "parallel"
      when: never
    - if: $RUN_NO_TESTS == "true"
      when: never
    - if: $PHP_UNIT_ALL_TESTS_BUILT_WITH_LDAP == "never"
      when: never
    - if: $RUN_ALL_TESTS == "true"
      when: on_success
    - if: $PHP_UNIT_ALL_TESTS_BUILT_WITH_LDAP == "true"
      when: on_success
    - when: never